language: python
python:
- '3.5'
env:
  global:
    - GH_REPO="github.com/firsttris/repository.sendtokodi.git"
    - YOUTUBE_DL="https://github.com/rg3/youtube-dl/archive/master.zip"
    - VERSION=0.0.${TRAVIS_JOB_NUMBER}
    - ADDON_NAME="plugin.video.sendtokodi"
    - ADDON_NAME_PYTHON3="plugin.video.sendtokodi.python3"
    - REPO_NAME="repository.sendtokodi"
    - NAME_PYTHON3="sendtokodi-python3"
    - NAME="sendtokodi"
script:
- rm -rf .git/
- envsubst < "addon.template.xml" > "addon.xml"
- cd ..
# clone repo
- git clone https://${GH_REPO}
# youtube_dl
- wget ${YOUTUBE_DL}
- unzip master.zip
- cp -R youtube-dl-master/youtube_dl ${ADDON_NAME}
# create python 2 version
- zip -r ${ADDON_NAME}-${VERSION}.zip ${ADDON_NAME}
- mkdir -p ${REPO_NAME}/${ADDON_NAME}/
- cp ${ADDON_NAME}/addon.xml ${REPO_NAME}/${ADDON_NAME}/
- cp ${ADDON_NAME}-${VERSION}.zip ${REPO_NAME}/${ADDON_NAME}/
# create python 3 addon.xml
- cd ${ADDON_NAME}
- rm addon.xml
- envsubst < "addon.template.python3.xml" > "addon.xml"
- cd ..
# create python 3 version
- zip -r ${ADDON_NAME_PYTHON3}-${VERSION}.zip ${ADDON_NAME}
- mkdir -p ${REPO_NAME}/${ADDON_NAME_PYTHON3}/
- cp ${ADDON_NAME}/addon.xml ${REPO_NAME}/${ADDON_NAME_PYTHON3}/
- cp ${ADDON_NAME_PYTHON3}-${VERSION}.zip ${REPO_NAME}/${ADDON_NAME_PYTHON3}/
# commit to repository
- cd ${REPO_NAME}/
- envsubst < "addon.template.xml" > "addon.xml"
- md5sum addon.xml > addon.xml.md5
- git add .
- git commit -m "Travis-CI Update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1