name: build-publish-addon
on:
  push:
    branches:
      - 'master'
env:
  VERSION: 'undefined'
  TOKEN: ${{secrets.PAT}}
jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: 'master'
  build:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build addon
        run: $GITHUB_WORKSPACE/.github/scripts/build-addon.sh ${{ needs.versioning.outputs.VERSION }}
      - name: Upload Addon-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Addon-artifacts
          path: "${{ runner.temp }}/*.zip"
  publish:
    needs: [versioning, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Addon-artifacts
      - name: Publish addon
        run: $GITHUB_WORKSPACE/.github/scripts/publish-addon.sh "github.com/firsttris/repository.sendtokodi.git" 
