name: build-master
# Changes to documentation alone don't build.
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
jobs:
  tests:
    uses: ./.github/workflows/reusable-tests.yml
    with:
      upload_coverage: true
      coverage_artifact_name: coverage-report
    secrets: inherit
